### ISSUE TITLE
support class based TypedDict syntax

### ISSUE THREAD

**Issue by graingert** [Gowee/json2pyi#1] opened 2021-12-10 12:44 UTC
first of all thanks a lot for this tool! It did *almost* exactly what I needed

https://www.python.org/dev/peps/pep-0589/#class-based-syntax

currently json2pyi generates:

```python
Move = TypedDict("Movie", {"name": str, "year": int})
```

but I'd like it to generate:
```python
class Movie(TypedDict):
    name: str
    year: int
```

where possible

**Comment by Gowee** [comment] 2021-12-10 13:23
Thanks for your suggestion! It turns out I overlooked that section. 

The class-based format looks trivial to adapt to. I will look into PEP589 carefully later.

**Comment by Gowee** [comment] 2021-12-12 15:08
I've made a quick fix by https://github.com/Gowee/json2pyi/commit/1955a93db98e1059a39d86143a7cf65106409715. It will take a while to be deployed :rocket: onto the web app: https://json2pyi.pages.dev/#TypedDictClass.

**Comment by Gowee** [comment] 2022-01-20 03:27
I just remember that the missing class-based `TypedDict` was due to regression after a refactor.

Should be fixed. Closing it for now. Please let me know if there are any other problems. Thanks!

**Closed as completed by Gowee** 2022-01-20 03:27 UTC
